In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty([2, 2])
print("1. Empty array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print("\n3. Array filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros-like array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\n5. Ones-like array:\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy array:\n", numpy_array)

1. Empty array (2x2):
 [[5.02014938e-310 0.00000000e+000]
 [            nan 1.76125651e-312]]

2. All-ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros-like array:
 [[0 0 0]
 [0 0 0]]

5. Ones-like array:
 [[1 1 1]
 [1 1 1]]

6. Converted NumPy array:
 [1 2 3 4]


In [ ]:
# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("1. Array with values ranging from 10 to 49:\n", array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:\n", matrix_0_to_8)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array (size 30):\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 array with random values:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\n7. Reversed array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)


1. Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30):
 [0.91335556 0.57572875 0.1345342  0.05134021 0.78715711 0.43668061
 0.53619086 0.93701535 0.04949442 0.81060224 0.91599739 0.60154922
 0.60771262 0.96305601 0.93272554 0.13589978 0.8826766  0.073548
 0.29787235 0.26765031 0.72012591 0.92155879 0.4802709  0.80532651
 0.75110189 0.03711751 0.87230333 0.63876954 0.93513031 0.41589323]
Mean of the array: 0.5829461688431805

5. 10x10 array with random values:
 [[0.18611509 0.95568057 0.04763243 0.49995006 0.79052469 0.57509616
  0.63558676 0.78823494 0.95162925 0.71389851]
 [0.21142421 0.22768025 0.97070256 0.08150474 0.28869672 0.68305968
  0.56381615 0.74806947 0.23113322 0.80162879]
 [0.10788732 0.22745089 0.408745

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition = x + y
print("1. Addition of x and y:\n", addition)

# 2. Subtract the two arrays
subtraction = x - y
print("\n2. Subtraction of x and y:\n", subtraction)

# 3. Multiply the array x with an integer (e.g., 3)
multiplication = x * 3
print("\n3. Multiplication of x with 3:\n", multiplication)

# 4. Find the square of each element of x
square = x**2
print("\n4. Square of each element in x:\n", square)

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5a. Dot product of v and w:", dot_vw)
print("5b. Dot product of x and v:\n", dot_xv)
print("5c. Dot product of x and y:\n", dot_xy)

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\n6a. Concatenation of x and y along rows:\n", concat_xy_row)
print("6b. Concatenation of v and w along columns:\n", concat_vw_col)

# 7. Attempt to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Error while concatenating x and v:")
    print(e)


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5a. Dot product of v and w: 219
5b. Dot product of x and v:
 [29 77]
5c. Dot product of x and y:
 [[19 22]
 [50 58]]

6a. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity matrix)
# Compute A^-1 (inverse of A)
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)  # Compute A * A^-1
print("1. A * A^-1:\n", identity_matrix)
print("Is A * A^-1 equal to I?:", np.allclose(identity_matrix, np.eye(2)))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?:", np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_T = np.transpose(np.dot(A, B))  # Compute transpose of AB
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # Compute Bᵀ * Aᵀ
print("\n3. (AB)ᵀ:\n", AB_T)
print("BᵀAᵀ:\n", BT_AT)
print("Is (AB)ᵀ equal to BᵀAᵀ?:", np.allclose(AB_T, BT_AT))


1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^-1 equal to I?: True

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA?: False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Is (AB)ᵀ equal to BᵀAᵀ?: True


In [ ]:
#For the following arrays:
#A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
#Prove following with Numpy:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

#Compute the determinant of A manually
det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

#Compute the cofactor matrix

cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

#Compute the adjoint (transpose of cofactor matrix)
adjoint_A = cofactor_matrix.T

#Compute the inverse of A
inverse_A = adjoint_A / det_A
print("\nInverse of A:\n", inverse_A)

#Solve for X = A⁻¹B
X = np.dot(inverse_A, B)
print("\nSolution (x, y, z):", X)

Determinant of A: -19

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
import numpy as np

# Define matrix A and vector B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the solution
print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
import time

A=[i for i in range(1000000)]
B=[i for i in range(1000000)]

start_time=time.time()
result_list=[A[i]+B[i] for i in range(1000000)]
end_time=time.time()
print(f"The addidtion of Two list {end_time-start_time:5f}")

an=np.array(1000000)
bn=np.array(1000000)

starttime=time.time()
addition=an+bn
endtime=time.time()
print(f"The addidtion of Two numpy array {endtime-starttime:5f}")


The addidtion of Two list 0.145813
The addidtion of Two numpy array 0.000097


In [ ]:
import time

A=[i for i in range(1000000)]
B=[i for i in range(1000000)]

start_time=time.time()
result_list=[A[i]*B[i] for i in range(1000000)]
end_time=time.time()
print(f"The addidtion of Two list {end_time-start_time:5f}")

an=np.array(1000000)
bn=np.array(1000000)

starttime=time.time()
multiplication=an*bn
endtime=time.time()
print(f"The addidtion of Two numpy array {endtime-starttime:5f}")

The addidtion of Two list 0.339078
The addidtion of Two numpy array 0.000118


In [ ]:
import time

A=[i for i in range(1000000)]
B=[i for i in range(1000000)]

start_time=time.time()
result_list=sum([A[i]*B[i] for i in range(1000000)])
end_time=time.time()
print(f"The addidtion of Two list {end_time-start_time:5f}")

an=np.array(1000000)
bn=np.array(1000000)

starttime=time.time()
multiplication=np.dot(an,bn)
endtime=time.time()
print(f"The addidtion of Two numpy array {endtime-starttime:5f}")

The addidtion of Two list 0.203928
The addidtion of Two numpy array 0.000110


In [2]:
import time
import numpy as np

A=[i for i in range(1000000)]
B=[i for i in range(1000000)]

start_time=time.time()
result_list=[A[i]*B[i] for i in range(1000000)]
end_time=time.time()
print(f"The addidtion of Two list {end_time-start_time:5f}")

an=np.array(1000000)
bn=np.array(1000000)

starttime=time.time()
multiplication=an*bn
endtime=time.time()
print(f"The addidtion of Two numpy array {endtime-starttime:5f}")

The addidtion of Two list 0.193386
The addidtion of Two numpy array 0.003343


In [4]:
import numpy as np
import random
import time

# Define the matrix size
size = 100

# Generate two 1000x1000 matrices using Python lists
matrix_a = [[random.random() for _ in range(size)] for _ in range(size)]
matrix_b = [[random.random() for _ in range(size)] for _ in range(size)]

# Function to perform matrix multiplication using lists
def matrix_multiplication_lists(matrix_a, matrix_b):
    result = [[0 for _ in range(len(matrix_b[0]))] for _ in range(len(matrix_a))]
    for i in range(len(matrix_a)):
        for j in range(len(matrix_b[0])):
            for k in range(len(matrix_b)):
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]
    return result

# Measure time for Python list-based multiplication
start_time = time.time()
matrix_multiplication_lists(matrix_a, matrix_b)
list_time = time.time() - start_time
print(f"Python Lists Time: {list_time:.2f} seconds")

# Generate two 1000x1000 matrices using NumPy
matrix_a_np = np.random.rand(size, size)
matrix_b_np = np.random.rand(size, size)

# Measure time for NumPy array-based multiplication
start_time = time.time()
np.dot(matrix_a_np, matrix_b_np)
numpy_time = time.time() - start_time
print(f"NumPy Time: {numpy_time:.2f} seconds")


Python Lists Time: 0.18 seconds
NumPy Time: 0.01 seconds
